---
- import_playbook: playbooks/docker-certificate/main.yml
- import_playbook: playbooks/docker/main.yml
- import_playbook: playbooks/docker-certificate/manager-certificate.yml
- import_playbook: playbooks/docker-swarm/main.yml