- hosts: docker
  become: yes

  vars_files:
    - vars.yml
  
  pre_tasks:
    - name: Create Docker configuration directories
      file:
        path: "{{ item }}"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0755"
      loop:
        - "/etc/docker"
        - "/etc/systemd/system/docker.service.d"

  roles:
    - geerlingguy.firewall
    - geerlingguy.docker

