---
firewall_flush_rules_and_chains: false
firewall_allowed_tcp_ports:
- "22"
- "80"
- "2376"
- "2377"
- "2368"
pip_install_packages:
 - name: docker
 - name: jsondiff
 - name: pyyaml
docker_users: ["vagrant"]
docker_daemon_options:
  storage-driver: "devicemapper"
  debug: true
  storage-opts: ["dm.basesize=40G","dm.use_deferred_deletion=true","dm.use_deferred_removal=true"]
  hosts: ["fd://","{{ host_daemon_tcp }}"]
  tls: true
  tlscert: "/etc/docker/server-cert.pem"
  tlskey: "/etc/docker/server-key.pem"
  tlscacert: "/etc/docker/ca.pem"
  tlsverify: true
docker__daemon_flags: ""
docker_package: "docker-{{ docker_edition }}-20.10.10"