# generate_client_certs.yml

- name: Create client key
  command: "openssl genrsa -out {{ dds_temp_path }}/key.pem 4096"
  changed_when: false


- name: Create client CSR
  command: "openssl req -subj '/CN=client' -new -key {{ dds_temp_path }}/key.pem -out {{ dds_temp_path }}/client.csr"
  changed_when: false


- name: Remove extfile
  file:
    state: absent
    path: "{{ dds_extfile }}"
    mode: 0644

- name: Create extfile
  file:
    state: touch
    path: "{{ dds_extfile }}"
    mode: 0644


- name: Add extendedKeyUsage to extfile
  lineinfile:
    dest: "{{ dds_extfile }}"
    line: "extendedKeyUsage = clientAuth"


- name: Create the client certificate
  command: "{{ create_client_certificate }}"
  changed_when: false


- name: Check that the client cert path exists
  file:
    state: directory
    path: "{{ dds_client_cert_path }}"
    mode: 0644


- name: Copy client certs
  command: cp "{{ dds_temp_path }}/{{ item }}" "{{ dds_client_cert_path }}/."
  with_items:
    - ca.pem
    - cert.pem
    - key.pem


- name: Set file permissions for keys
  file:
    path: "{{ dds_client_cert_path }}/{{ item }}"
    mode: 0400
  with_items:
    - key.pem


- name: Set file permissions
  file:
    path: "{{ dds_client_cert_path }}/{{ item }}"
    mode: 0444
  with_items:
    - ca.pem
    - cert.pem
