# generate_server_certs.yml 

- name: Create server key
  command: openssl genrsa -out {{ dds_temp_path }}/server-key.pem 4096
  changed_when: false

- name: Create the server CSR
  command: "{{ create_server_csr }}"
  changed_when: false

- name: Remove extfile
  file:
    state: absent
    path: "{{ dds_extfile }}"
    mode: 0644

- name: Create extfile
  file:
    state: touch
    path: "{{ dds_extfile }}"
    mode: 0644

- name: Add alt name to extfile
  lineinfile:
    dest: "{{ dds_extfile }}"
    line: "subjectAltName = IP:{{ dds_host | default('127.0.0.1') }},IP:127.0.0.1"

- name: Create the server certificate
  command: "{{ create_server_certificate }}"
  changed_when: false

- name: Check that the server cert path exists
  file:
    state: directory
    path: "{{ dds_server_cert_path }}"
  tags: skip_this_rule

- name: Copy server certs
  command: cp "{{ dds_temp_path }}/{{ item }}" "{{ dds_server_cert_path }}/."
  with_items:
    - ca.pem
    - server-cert.pem
    - server-key.pem
  changed_when: false

- name: Set file permissions for keys
  file:
    path: "{{ dds_server_cert_path }}/{{ item }}"
    mode: 0400
  with_items:
    - server-key.pem

- name: Set file permissions
  file:
    path: "{{ dds_server_cert_path }}/{{ item }}"
    mode: 0400
  with_items:
    - ca.pem
    - server-cert.pem
