- hosts: docker_swarm_manager
  become: yes

  vars_files:
    - vars.yml
    
  tasks:
    - name: Copy Client Certificate Files to local machine
      fetch:
        src: "{{dds_client_cert_path}}/{{ item }}"
        dest: "~/.docker/"
        flat: yes
        force: yes
      when: "inventory_hostname == groups['docker_swarm_manager'][0]"
      with_items:
        - ca.pem
        - cert.pem
        - key.pem